version: '3.4'

services:
  webpack:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: watch
    volumes:
      - ./build:/opt/server/build:rw
      - ./dist:/opt/server/dist:rw
      - ./resources:/opt/server/resources:ro
      - ./src:/opt/server/src:ro

  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: start
    env_file: .env
    ports:
      - 8080:8080
    volumes:
      - ./build:/opt/server/build:ro
      - ./dist:/opt/server/dist:ro
      - ./resources:/opt/server/resources:ro
